version: 2.1

orbs:
    maven: circleci/maven@1.0.1

jobs:
    build:
        working_directory: ~/javaCi

        steps:
            - checkout
            - run: compile
    test:
        working_directory: ~/javaCi

        steps:
            - checkout
            - run: mvn test

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build
            - test
