version: 2.1

jobs:
    build:
        docker:
            - image: circleci/maven:1.0.1

        working_directory: ~/javaCi

        steps:
            - checkout
            - run: compile
    test:
        docker:
            - image: circleci/maven:1.0.1

        working_directory: ~/javaCi

        steps:
            - checkout
            - run: mvn test

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build
            - test
